[project]
name = "tips"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mirascope[anthropic,openai]>=1.22.4",
    "pydantic>=2.11.4",
]
